### ISSUE TITLE
Depend on dmstr/yii2-adminlte-asset?

### ISSUE THREAD

**Issue by schmunk42** [Insolita/yii2-adminlte-widgets#1]
FYI: We've a ready to use asset bundle: https://github.com/dmstr/yii2-adminlte-asset

I think about using your widgets, but I think you've some hardcoded dependencies to common?

**Comment by Insolita** [comment]
You can change dependency 

``` php
     'assetManager'=>[
                 'class'=>'yii\web\AssetManager',
                 'bundles'=>[
                 //--------
                     'insolita\wgadminlte\ExtAdminlteAsset'=>[
                         'depends'=>[
                             'dmstr\web\AdminLteAsset'
                         ]
                     ]

             ],
```

**Comment by schmunk42** [comment]
Just thought it would be helpful for you, if you could depend on an existing available bundle.
Please close this ticket if it does not apply.

**Comment by Insolita** [comment]
I  really not see reason for set dependency of  any Adminlte asset bundle, or make own. ExtAdminlteAsset provide script for remember collapsing state, and has a positional dependency only, and you easily change it via the assetManager.  I can only remove hardcode dependecy of common\assets\AdminLTE
