### ISSUE TITLE
Setting unknown property: insolita\wgadminlte\Timeline::dataFunc

### ISSUE THREAD

**Issue by evgeniy123** [Insolita/yii2-adminlte-widgets#11]
hello. I do just copy past and get this message
`why I get `

code:

`<?= \insolita\wgadminlte\Timeline::widget(
    [
        'defaultDateBg' => \insolita\wgadminlte\Timeline::TYPE_PURPLE, //default background for deate label
        'items' => [
            '1381767094'=>[
                Yii::createObject(
                    [
                        'class' => \insolita\wgadminlte\TimelineItem::className(),
                        'time' => 1381767094,
                        'header' =>'SOME HEADER',
                        'body' => 'Well, i`m informative body',
                                         'iconClass'=>'fa fa-beer',
                                         'iconBg'=>'orange'
                                     ]
                                 ),
                         Yii::createObject(
                             [
                                 'class' => \insolita\wgadminlte\TimelineItem::className(),
                                 'time' => 1381767098,
                                 'header' =>'SOME HEADER',
                                 'iconClass'=>'fa fa-beer',
                                 'iconBg'=>'green'
                             ]
                         )

					],
					'1400880100'=>[
    Yii::createObject(
        [
            'class' => \insolita\wgadminlte\TimelineItem::className(),
            'time' => 1400880100,
            'body' => 'Well, im informative body',
                                        'iconClass'=>'fa fa-cloud',
                                        'iconBg'=>insolita\wgadminlte\Timeline::TYPE_BLUE
                                    ]
                                ),
                                 ],
            ],
            'dataFunc' => function ($data) { return date('d.m, Y', $data); }
        ]
    ) ?>` 
Where is the problem ? please

**Comment by Insolita** [comment]
'dataFunc'  is property for whole Timeline object, not concrete item

**Comment by evgeniy123** [comment]
ah ok
