### ISSUE TITLE
collapsebox.js - Cannot set property 'activate' of undefined

### ISSUE THREAD

**Issue by philippfrenzel** [Insolita/yii2-adminlte-widgets#12]
Uncaught TypeError: Cannot set property 'activate' of undefined
    at HTMLDocument.<anonymous> (collapsebox.js:4)
    at fire (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at Function.ready (jquery.js:3536)
    at HTMLDocument.completed (jquery.js:3552)

**Comment by Insolita** [comment]
Check your assetManager configuration,  are you set dependencies correctly ? 

```php
 'assetManager'=>[
                 'class'=>'yii\web\AssetManager',
                 'bundles'=>[
                 //--------
                     'insolita\wgadminlte\ExtAdminlteAsset'=>[
                         'depends'=>[
                             'yii\web\YiiAsset',
                             'path\to\AdminLteAsset',
                             'insolita\wgadminlte\JsCookieAsset'
                         ]
                     ],
                     'insolita\wgadminlte\JsCookieAsset'=>[
                           'depends'=>[
                               'yii\web\YiiAsset',
                               'path\to\AdminLteAsset'
                          ]
                     ],

             ],
     ]

```

collapsebox.js must be after main adminlte script

**Comment by Insolita** [comment]
What version of adminlte you use?  2.4 version has changes with box plugin, as i see. Try 2.3.

**Comment by philippfrenzel** [comment]
I guess it's 2.4 -> ok - so need to "downgrade" it ;)

**Comment by schmunk42** [comment]
One issue here is that the assets in this extension `depend` on an external `AdmineLteAsset`, like https://github.com/dmstr/yii2-adminlte-asset.

The solution from @Insolita above redefines the dependencies, so the base AdminLTE asset is included first, but it's kinda tricky solution, since we have to override all the depends from asset-bundles here.
