### ISSUE TITLE
[bug] Refresh box states after pjax reload

### ISSUE THREAD

**Issue by bscheshirwork** [Insolita/yii2-adminlte-widgets#17]
How to rebuild actions after pjax redraw content with box `\insolita\wgadminlte\CollapseBox`?

Подскажите, как восстановить действия, привязанные к заголовку виджета `\insolita\wgadminlte\CollapseBox` . после pjax обновления содержащего этот виджет контента? 
`'collapseRemember' => true,`
После обновления блок полностью развернут, кнопка не реагирует на нажатия. Насколько понял, из-за привязки событий к id, а не к css классу.

https://github.com/defunkt/jquery-pjax#reinitializing-pluginswidget-on-new-page-content

```js
$(document).on('ready pjax:end', function(event) {
  $(event.target).initializeMyPlugin()
})
```

Спасибо.

**Comment by Insolita** [comment]
hmm, currently this case is not supported
will fix it soon

(Это не зависит от привязки к id или классу)

**Comment by Insolita** [comment]
Update to latest version and add this code in view where pjax widget used

```php
<?php
  $this->registerJs('
       $(document).on("pjax:end", function() {
            LteBox.init();
       });
  ');
?>
```
